name: "Main"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - "**"

jobs:
  get_fvm_version:
    outputs:
      fvm_version: ${{ steps.fvm_version.outputs.version }}
    name: "Get Flutter version from FVM"
    runs-on: ubuntu-latest
    steps:
      - id: fvm_version
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: ".fvm/fvm_config.json"
      - run: echo "version=${{steps.fvm_version.outputs.flutterSdkVersion}}" >> "$GITHUB_OUTPUT"

  analysis:
    needs: get_fvm_version
    uses: surfstudio/flutter-ci-workflows/.github/workflows/analysis.yml@main
    with:
      flutter-version: ${{ needs.get_fvm_version.outputs.output1 }}

  testing:
    needs: [analysis, get_fvm_version]
    uses: surfstudio/flutter-ci-workflows/.github/workflows/testing.yml@main
    with:
      flutter-version: ${{ needs.get_fvm_version.outputs.output1 }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build_android_example:
    needs: [analysis, get_fvm_version]
    uses: surfstudio/flutter-ci-workflows/.github/workflows/build_android_example.yml@main
    with:
      flutter-version: ${{ needs.get_fvm_version.outputs.output1 }}

  build_ios_example:
    needs: [analysis, get_fvm_version]
    uses: surfstudio/flutter-ci-workflows/.github/workflows/build_ios_example.yml@main
    with:
      flutter-version: ${{ needs.get_fvm_version.outputs.output1 }}
