# This workflow is triggered when a pull request opened, edited, reopened,
# converted_to_draft and ready_for_review.
#
# There is no WIP in the title, there is no WIP label and the pull request is not a draft the
# new pull request label is added.
# If either of these is true then remove the label new pull request if there is one.

name: Pull-request tracking
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - converted_to_draft
      - ready_for_review

jobs:
  pull_request:
    uses: surfstudio/flutter-ci-workflows/.github/workflows/new_pull_request_label.yml@main
    secrets:
      SECRET_ISSUES: ${{ secrets.SECRET_ISSUES }}