# This workflow is triggered when a WIP label is added to an open pull request.
# When deleting the WIP label, the new_pull_request label is added.
# When adding a WIP label, the new_pull_request label is removed if there is one.

name: Pull-request label tracking
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled

jobs:
  label_pull_request:
    if: ${{ github.event.label.name == 'WIP' }}
    uses: surfstudio/flutter-ci-workflows/.github/workflows/new_pull_request_label.yml@main
    secrets:
      SECRET_ISSUES: ${{ secrets.SECRET_ISSUES }}
