name: "Create Pyrus task from issue"

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  get_package_name:
    name: Get package name
    runs-on: ubuntu-latest
    outputs:
      package_name: ${{ steps.parse_pubspec.outputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Parsing pubspec.yaml
        id: parse_pubspec
        uses: actions-tools/yaml-outputs@v2
        with:
          file-path: 'pubspec.yaml'

  call_create_pyrus_task_from_issue:
    name: Create Pyrus task from issue
    needs: get_package_name
    uses: surfstudio/flutter-ci-workflows/.github/workflows/new_issue_to_pyrus_task.yml@main
    with:
      PACKAGE_NAME: ${{ needs.get_package_name.outputs.package_name }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
      ISSUE_BODY: ${{ github.event.issue.body }}
      ISSUE_LINK: ${{ github.event.issue.html_url }}
    secrets:
      LOGIN: ${{ secrets.PYRUS_BOT_LOGIN }}
      SECURITY_KEY: ${{ secrets.PYRUS_BOT_SECRET_KEY }}
